### ISSUE TITLE
Updating the charm icon

### ISSUE THREAD

**Issue by kwm14** [cholcombe973/gluster-charm#33]
Hi,

The design team at Canonical would like to update charm icons to fit within the new circular format, as displayed in the current GUI.

This will improve how charms are displayed in the store, search results and on charm details pages.

I've attached a new version of the charm icon. If you're happy with this change, please could you update the icon and let us know when it's done.

[gluster.svg.zip](https://github.com/cholcombe973/gluster-charm/files/1177374/gluster.svg.zip)

Thanks

**Comment by cholcombe973** [comment]
Done.  Thank you!
